import { type Park } from '../types';

const NOW = 0;

type SeedPark = Omit<Park, 'lastSynced' | 'rawJson' | 'activities' | 'entranceFeeCents' | 'imageUrl' | 'description'>;

const SEEDS: SeedPark[] = [
  // ── Alabama ──────────────────────────────────────────────────────────────
  { id: 'seed_al_blue_springs', source: 'state', fullName: 'Blue Springs State Park', stateCodes: 'AL', latitude: 31.7138, longitude: -85.5971, designation: 'State Park' },
  { id: 'seed_al_bucks_pocket', source: 'state', fullName: "Buck's Pocket State Park", stateCodes: 'AL', latitude: 34.3743, longitude: -86.0588, designation: 'State Park' },
  { id: 'seed_al_cathedral_caverns', source: 'state', fullName: 'Cathedral Caverns State Park', stateCodes: 'AL', latitude: 34.5954, longitude: -86.2116, designation: 'State Park' },
  { id: 'seed_al_cheaha', source: 'state', fullName: 'Cheaha State Park', stateCodes: 'AL', latitude: 33.4854, longitude: -85.8093, designation: 'State Park' },
  { id: 'seed_al_chewacla', source: 'state', fullName: 'Chewacla State Park', stateCodes: 'AL', latitude: 32.5385, longitude: -85.4755, designation: 'State Park' },
  { id: 'seed_al_desoto', source: 'state', fullName: 'DeSoto State Park', stateCodes: 'AL', latitude: 34.4968, longitude: -85.6208, designation: 'State Park' },
  { id: 'seed_al_frank_jackson', source: 'state', fullName: 'Frank Jackson State Park', stateCodes: 'AL', latitude: 31.2785, longitude: -86.2763, designation: 'State Park' },
  { id: 'seed_al_gulf', source: 'state', fullName: 'Gulf State Park', stateCodes: 'AL', latitude: 30.2627, longitude: -87.6694, designation: 'State Park' },
  { id: 'seed_al_joe_wheeler', source: 'state', fullName: 'Joe Wheeler State Park', stateCodes: 'AL', latitude: 34.8279, longitude: -87.3222, designation: 'State Park' },
  { id: 'seed_al_lake_guntersville', source: 'state', fullName: 'Lake Guntersville State Park', stateCodes: 'AL', latitude: 34.3787, longitude: -86.2088, designation: 'State Park' },
  { id: 'seed_al_lake_lurleen', source: 'state', fullName: 'Lake Lurleen State Park', stateCodes: 'AL', latitude: 33.2660, longitude: -87.5671, designation: 'State Park' },
  { id: 'seed_al_lakepoint', source: 'state', fullName: 'Lakepoint Resort State Park', stateCodes: 'AL', latitude: 31.9835, longitude: -85.0809, designation: 'State Park' },
  { id: 'seed_al_meaher', source: 'state', fullName: 'Meaher State Park', stateCodes: 'AL', latitude: 30.6696, longitude: -87.9120, designation: 'State Park' },
  { id: 'seed_al_monte_sano', source: 'state', fullName: 'Monte Sano State Park', stateCodes: 'AL', latitude: 34.7527, longitude: -86.5052, designation: 'State Park' },
  { id: 'seed_al_oak_mountain', source: 'state', fullName: 'Oak Mountain State Park', stateCodes: 'AL', latitude: 33.3593, longitude: -86.7116, designation: 'State Park' },
  { id: 'seed_al_rickwood_caverns', source: 'state', fullName: 'Rickwood Caverns State Park', stateCodes: 'AL', latitude: 33.8321, longitude: -86.8254, designation: 'State Park' },
  { id: 'seed_al_roland_cooper', source: 'state', fullName: 'Roland Cooper State Park', stateCodes: 'AL', latitude: 31.9474, longitude: -87.2669, designation: 'State Park' },
  { id: 'seed_al_wind_creek', source: 'state', fullName: 'Wind Creek State Park', stateCodes: 'AL', latitude: 32.8871, longitude: -85.9385, designation: 'State Park' },
  { id: 'seed_al_bladon_springs', source: 'state', fullName: 'Bladon Springs State Park', stateCodes: 'AL', latitude: 31.7652, longitude: -88.0879, designation: 'State Park' },
  { id: 'seed_al_chickasaw', source: 'state', fullName: 'Chickasaw State Park', stateCodes: 'AL', latitude: 32.2543, longitude: -87.8027, designation: 'State Park' },
  { id: 'seed_al_paul_grist', source: 'state', fullName: 'Paul M. Grist State Park', stateCodes: 'AL', latitude: 32.4271, longitude: -87.0835, designation: 'State Park' },
  { id: 'seed_al_blakeley', source: 'state', fullName: 'Historic Blakeley State Park', stateCodes: 'AL', latitude: 30.7257, longitude: -87.8671, designation: 'State Historic Park' },
  { id: 'seed_al_brierfield', source: 'state', fullName: 'Brierfield Ironworks Historical State Park', stateCodes: 'AL', latitude: 33.0437, longitude: -86.9376, designation: 'State Historic Park' },
  { id: 'seed_al_tannehill', source: 'state', fullName: 'Tannehill Ironworks Historical State Park', stateCodes: 'AL', latitude: 33.3616, longitude: -87.0785, designation: 'State Historic Park' },

  // ── Alaska ───────────────────────────────────────────────────────────────
  { id: 'seed_ak_chugach', source: 'state', fullName: 'Chugach State Park', stateCodes: 'AK', latitude: 61.1670, longitude: -149.3530, designation: 'State Park' },
  { id: 'seed_ak_denali', source: 'state', fullName: 'Denali State Park', stateCodes: 'AK', latitude: 62.5357, longitude: -150.1476, designation: 'State Park' },
  { id: 'seed_ak_wood_tikchik', source: 'state', fullName: 'Wood-Tikchik State Park', stateCodes: 'AK', latitude: 59.6972, longitude: -158.6528, designation: 'State Park' },
  { id: 'seed_ak_kachemak_bay', source: 'state', fullName: 'Kachemak Bay State Park', stateCodes: 'AK', latitude: 59.5975, longitude: -151.2125, designation: 'State Park' },
  { id: 'seed_ak_lake_aleknagik', source: 'state', fullName: 'Lake Aleknagik State Recreation Area', stateCodes: 'AK', latitude: 59.2833, longitude: -158.6167, designation: 'State Recreation Area' },
  { id: 'seed_ak_nancy_lake', source: 'state', fullName: 'Nancy Lake State Recreation Area', stateCodes: 'AK', latitude: 61.6803, longitude: -150.0508, designation: 'State Recreation Area' },
  { id: 'seed_ak_chena_river', source: 'state', fullName: 'Chena River State Recreation Area', stateCodes: 'AK', latitude: 64.7500, longitude: -146.5000, designation: 'State Recreation Area' },
  { id: 'seed_ak_delta', source: 'state', fullName: 'Delta State Recreation Site', stateCodes: 'AK', latitude: 64.0380, longitude: -145.7276, designation: 'State Recreation Area' },
  { id: 'seed_ak_eklutna_lake', source: 'state', fullName: 'Eklutna Lake State Recreation Area', stateCodes: 'AK', latitude: 61.4494, longitude: -149.1550, designation: 'State Recreation Area' },
  { id: 'seed_ak_finger_lake', source: 'state', fullName: 'Finger Lake State Recreation Area', stateCodes: 'AK', latitude: 61.6167, longitude: -149.4833, designation: 'State Recreation Area' },
  { id: 'seed_ak_keystone_canyon', source: 'state', fullName: 'Keystone Canyon State Recreation Site', stateCodes: 'AK', latitude: 61.3700, longitude: -145.7200, designation: 'State Recreation Area' },
  { id: 'seed_ak_halibut_point', source: 'state', fullName: 'Halibut Point State Recreation Site', stateCodes: 'AK', latitude: 57.0736, longitude: -135.3697, designation: 'State Recreation Area' },
  { id: 'seed_ak_williwaw', source: 'state', fullName: 'Williwaw State Recreation Site', stateCodes: 'AK', latitude: 60.8167, longitude: -148.9167, designation: 'State Recreation Area' },
  { id: 'seed_ak_totem_bight', source: 'state', fullName: 'Totem Bight State Historical Park', stateCodes: 'AK', latitude: 55.4192, longitude: -131.7384, designation: 'State Historic Park' },
  { id: 'seed_ak_independence_mine', source: 'state', fullName: 'Independence Mine State Historical Park', stateCodes: 'AK', latitude: 61.7714, longitude: -149.2983, designation: 'State Historic Park' },
  { id: 'seed_ak_big_delta', source: 'state', fullName: 'Big Delta State Historical Park', stateCodes: 'AK', latitude: 64.1533, longitude: -145.8367, designation: 'State Historic Park' },
  { id: 'seed_ak_shoup_bay', source: 'state', fullName: 'Shoup Bay State Marine Park', stateCodes: 'AK', latitude: 61.1200, longitude: -146.5500, designation: 'State Marine Park' },
  { id: 'seed_ak_surprise_cove', source: 'state', fullName: 'Surprise Cove State Marine Park', stateCodes: 'AK', latitude: 60.9167, longitude: -148.1667, designation: 'State Marine Park' },
  { id: 'seed_ak_decision_point', source: 'state', fullName: 'Decision Point State Marine Park', stateCodes: 'AK', latitude: 60.9833, longitude: -148.3000, designation: 'State Marine Park' },
  { id: 'seed_ak_halibut_cove', source: 'state', fullName: 'Halibut Cove State Marine Park', stateCodes: 'AK', latitude: 59.5950, longitude: -151.2167, designation: 'State Marine Park' },

  // ── Arizona ──────────────────────────────────────────────────────────────
  { id: 'seed_az_alamo_lake', source: 'state', fullName: 'Alamo Lake State Park', stateCodes: 'AZ', latitude: 34.2361, longitude: -113.5694, designation: 'State Park' },
  { id: 'seed_az_buckskin_mountain', source: 'state', fullName: 'Buckskin Mountain State Park', stateCodes: 'AZ', latitude: 34.1806, longitude: -114.1319, designation: 'State Park' },
  { id: 'seed_az_catalina', source: 'state', fullName: 'Catalina State Park', stateCodes: 'AZ', latitude: 32.4186, longitude: -110.9230, designation: 'State Park' },
  { id: 'seed_az_cattail_cove', source: 'state', fullName: 'Cattail Cove State Park', stateCodes: 'AZ', latitude: 34.3972, longitude: -114.1833, designation: 'State Park' },
  { id: 'seed_az_dead_horse_ranch', source: 'state', fullName: 'Dead Horse Ranch State Park', stateCodes: 'AZ', latitude: 34.7387, longitude: -112.0012, designation: 'State Park' },
  { id: 'seed_az_fool_hollow', source: 'state', fullName: 'Fool Hollow Lake Recreation Area', stateCodes: 'AZ', latitude: 34.1631, longitude: -110.0156, designation: 'State Recreation Area' },
  { id: 'seed_az_lake_havasu', source: 'state', fullName: 'Lake Havasu State Park', stateCodes: 'AZ', latitude: 34.5200, longitude: -114.3500, designation: 'State Park' },
  { id: 'seed_az_lyman_lake', source: 'state', fullName: 'Lyman Lake State Park', stateCodes: 'AZ', latitude: 34.3708, longitude: -109.3722, designation: 'State Park' },
  { id: 'seed_az_patagonia_lake', source: 'state', fullName: 'Patagonia Lake State Park', stateCodes: 'AZ', latitude: 31.4667, longitude: -110.8500, designation: 'State Park' },
  { id: 'seed_az_picacho_peak', source: 'state', fullName: 'Picacho Peak State Park', stateCodes: 'AZ', latitude: 32.6431, longitude: -111.4025, designation: 'State Park' },
  { id: 'seed_az_red_rock', source: 'state', fullName: 'Red Rock State Park', stateCodes: 'AZ', latitude: 34.8667, longitude: -111.8333, designation: 'State Park' },
  { id: 'seed_az_roper_lake', source: 'state', fullName: 'Roper Lake State Park', stateCodes: 'AZ', latitude: 32.7167, longitude: -109.7500, designation: 'State Park' },
  { id: 'seed_az_slide_rock', source: 'state', fullName: 'Slide Rock State Park', stateCodes: 'AZ', latitude: 34.9397, longitude: -111.7541, designation: 'State Park' },
  { id: 'seed_az_tonto_natural_bridge', source: 'state', fullName: 'Tonto Natural Bridge State Park', stateCodes: 'AZ', latitude: 34.3253, longitude: -111.4514, designation: 'State Park' },
  { id: 'seed_az_burro_creek', source: 'state', fullName: 'Burro Creek State Park', stateCodes: 'AZ', latitude: 34.4667, longitude: -113.6500, designation: 'State Park' },
  { id: 'seed_az_fort_verde', source: 'state', fullName: 'Fort Verde State Historic Park', stateCodes: 'AZ', latitude: 34.5597, longitude: -111.8603, designation: 'State Historic Park' },
  { id: 'seed_az_jerome', source: 'state', fullName: 'Jerome State Historic Park', stateCodes: 'AZ', latitude: 34.7481, longitude: -112.1144, designation: 'State Historic Park' },
  { id: 'seed_az_mcfarland', source: 'state', fullName: 'McFarland State Historic Park', stateCodes: 'AZ', latitude: 33.0314, longitude: -111.3875, designation: 'State Historic Park' },
  { id: 'seed_az_tubac_presidio', source: 'state', fullName: 'Tubac Presidio State Historic Park', stateCodes: 'AZ', latitude: 31.5667, longitude: -111.0500, designation: 'State Historic Park' },
  { id: 'seed_az_tombstone_courthouse', source: 'state', fullName: 'Tombstone Courthouse State Historic Park', stateCodes: 'AZ', latitude: 31.7128, longitude: -110.0669, designation: 'State Historic Park' },
  { id: 'seed_az_yuma_prison', source: 'state', fullName: 'Yuma Territorial Prison State Historic Park', stateCodes: 'AZ', latitude: 32.7236, longitude: -114.6222, designation: 'State Historic Park' },
  { id: 'seed_az_riordan_mansion', source: 'state', fullName: 'Riordan Mansion State Historic Park', stateCodes: 'AZ', latitude: 35.1939, longitude: -111.6481, designation: 'State Historic Park' },
  { id: 'seed_az_homolovi', source: 'state', fullName: 'Homolovi State Park', stateCodes: 'AZ', latitude: 35.0378, longitude: -110.6469, designation: 'State Historic Park' },
  { id: 'seed_az_colorado_river', source: 'state', fullName: 'Colorado River State Historic Park', stateCodes: 'AZ', latitude: 32.7167, longitude: -114.6333, designation: 'State Historic Park' },

  // ── Arkansas ─────────────────────────────────────────────────────────────
  { id: 'seed_ar_museum_natural_resources', source: 'state', fullName: 'Arkansas Museum of Natural Resources State Park', stateCodes: 'AR', latitude: 33.3667, longitude: -92.7333, designation: 'State Park' },
  { id: 'seed_ar_bull_shoals', source: 'state', fullName: 'Bull Shoals-White River State Park', stateCodes: 'AR', latitude: 36.3833, longitude: -92.5833, designation: 'State Park' },
  { id: 'seed_ar_cane_creek', source: 'state', fullName: 'Cane Creek State Park', stateCodes: 'AR', latitude: 33.9167, longitude: -91.7833, designation: 'State Park' },
  { id: 'seed_ar_cossatot_river', source: 'state', fullName: 'Cossatot River State Park-Natural Area', stateCodes: 'AR', latitude: 34.0333, longitude: -94.3500, designation: 'State Natural Area' },
  { id: 'seed_ar_crowleys_ridge', source: 'state', fullName: "Crowley's Ridge State Park", stateCodes: 'AR', latitude: 36.0500, longitude: -90.5167, designation: 'State Park' },
  { id: 'seed_ar_daisy', source: 'state', fullName: 'Daisy State Park', stateCodes: 'AR', latitude: 34.2667, longitude: -93.7833, designation: 'State Park' },
  { id: 'seed_ar_delta_heritage_trail', source: 'state', fullName: 'Delta Heritage Trail State Park', stateCodes: 'AR', latitude: 34.3000, longitude: -90.8667, designation: 'State Park' },
  { id: 'seed_ar_degray_lake', source: 'state', fullName: 'DeGray Lake Resort State Park', stateCodes: 'AR', latitude: 34.2333, longitude: -93.1500, designation: 'State Park' },
  { id: 'seed_ar_devils_den', source: 'state', fullName: "Devil's Den State Park", stateCodes: 'AR', latitude: 35.7833, longitude: -94.2333, designation: 'State Park' },
  { id: 'seed_ar_lake_catherine', source: 'state', fullName: 'Lake Catherine State Park', stateCodes: 'AR', latitude: 34.3167, longitude: -92.9667, designation: 'State Park' },
  { id: 'seed_ar_lake_dardanelle', source: 'state', fullName: 'Lake Dardanelle State Park', stateCodes: 'AR', latitude: 35.2833, longitude: -93.1500, designation: 'State Park' },
  { id: 'seed_ar_lake_fort_smith', source: 'state', fullName: 'Lake Fort Smith State Park', stateCodes: 'AR', latitude: 35.6167, longitude: -94.1333, designation: 'State Park' },
  { id: 'seed_ar_lake_ouachita', source: 'state', fullName: 'Lake Ouachita State Park', stateCodes: 'AR', latitude: 34.5667, longitude: -93.2333, designation: 'State Park' },
  { id: 'seed_ar_lake_poinsett', source: 'state', fullName: 'Lake Poinsett State Park', stateCodes: 'AR', latitude: 35.5667, longitude: -90.7167, designation: 'State Park' },
  { id: 'seed_ar_logoly', source: 'state', fullName: 'Logoly State Park', stateCodes: 'AR', latitude: 33.1167, longitude: -93.2000, designation: 'State Park' },
  { id: 'seed_ar_millwood', source: 'state', fullName: 'Millwood State Park', stateCodes: 'AR', latitude: 33.7333, longitude: -94.0333, designation: 'State Park' },
  { id: 'seed_ar_moro_bay', source: 'state', fullName: 'Moro Bay State Park', stateCodes: 'AR', latitude: 33.1333, longitude: -91.9833, designation: 'State Park' },
  { id: 'seed_ar_mount_nebo', source: 'state', fullName: 'Mount Nebo State Park', stateCodes: 'AR', latitude: 35.2333, longitude: -93.2500, designation: 'State Park' },
  { id: 'seed_ar_mount_magazine', source: 'state', fullName: 'Mount Magazine State Park', stateCodes: 'AR', latitude: 35.1667, longitude: -93.6333, designation: 'State Park' },
  { id: 'seed_ar_queen_wilhelmina', source: 'state', fullName: 'Queen Wilhelmina State Park', stateCodes: 'AR', latitude: 34.6833, longitude: -94.3833, designation: 'State Park' },
  { id: 'seed_ar_pinnacle_mountain', source: 'state', fullName: 'Pinnacle Mountain State Park', stateCodes: 'AR', latitude: 34.8167, longitude: -92.4833, designation: 'State Park' },
  { id: 'seed_ar_village_creek', source: 'state', fullName: 'Village Creek State Park', stateCodes: 'AR', latitude: 35.1167, longitude: -90.6500, designation: 'State Park' },
  { id: 'seed_ar_white_oak_lake', source: 'state', fullName: 'White Oak Lake State Park', stateCodes: 'AR', latitude: 33.7167, longitude: -93.3167, designation: 'State Park' },
  { id: 'seed_ar_withrow_springs', source: 'state', fullName: 'Withrow Springs State Park', stateCodes: 'AR', latitude: 36.1500, longitude: -93.7500, designation: 'State Park' },
  { id: 'seed_ar_davidsonville', source: 'state', fullName: 'Davidsonville Historic State Park', stateCodes: 'AR', latitude: 36.3667, longitude: -90.9833, designation: 'State Historic Park' },
  { id: 'seed_ar_powhatan', source: 'state', fullName: 'Powhatan Historic State Park', stateCodes: 'AR', latitude: 36.1167, longitude: -91.1000, designation: 'State Historic Park' },
  { id: 'seed_ar_prairie_grove', source: 'state', fullName: 'Prairie Grove Battlefield State Park', stateCodes: 'AR', latitude: 35.9833, longitude: -94.3167, designation: 'State Historic Park' },
  { id: 'seed_ar_toltec_mounds', source: 'state', fullName: 'Toltec Mounds Archeological State Park', stateCodes: 'AR', latitude: 34.6500, longitude: -92.0833, designation: 'State Historic Park' },
  { id: 'seed_ar_ozark_folk_center', source: 'state', fullName: 'Ozark Folk Center State Park', stateCodes: 'AR', latitude: 35.8667, longitude: -92.1167, designation: 'State Historic Park' },
  { id: 'seed_ar_lower_white_river', source: 'state', fullName: 'Lower White River Museum State Park', stateCodes: 'AR', latitude: 34.3542, longitude: -91.1292, designation: 'State Historic Park' },

  // ── California ───────────────────────────────────────────────────────────
  { id: 'seed_ca_anza_borrego', source: 'state', fullName: 'Anza-Borrego Desert State Park', stateCodes: 'CA', latitude: 33.2578, longitude: -116.3956, designation: 'State Park' },
  { id: 'seed_ca_big_basin', source: 'state', fullName: 'Big Basin Redwoods State Park', stateCodes: 'CA', latitude: 37.1741, longitude: -122.2230, designation: 'State Park' },
  { id: 'seed_ca_calaveras_big_trees', source: 'state', fullName: 'Calaveras Big Trees State Park', stateCodes: 'CA', latitude: 38.2743, longitude: -120.3133, designation: 'State Park' },
  { id: 'seed_ca_castle_crags', source: 'state', fullName: 'Castle Crags State Park', stateCodes: 'CA', latitude: 41.1572, longitude: -122.3133, designation: 'State Park' },
  { id: 'seed_ca_cuyamaca_rancho', source: 'state', fullName: 'Cuyamaca Rancho State Park', stateCodes: 'CA', latitude: 32.9500, longitude: -116.5833, designation: 'State Park' },
  { id: 'seed_ca_dl_bliss', source: 'state', fullName: 'D.L. Bliss State Park', stateCodes: 'CA', latitude: 38.9728, longitude: -120.1022, designation: 'State Park' },
  { id: 'seed_ca_emerald_bay', source: 'state', fullName: 'Emerald Bay State Park', stateCodes: 'CA', latitude: 38.9540, longitude: -120.1097, designation: 'State Park' },
  { id: 'seed_ca_angel_island', source: 'state', fullName: 'Angel Island State Park', stateCodes: 'CA', latitude: 37.8667, longitude: -122.4333, designation: 'State Park' },
  { id: 'seed_ca_julia_pfeiffer', source: 'state', fullName: 'Julia Pfeiffer Burns State Park', stateCodes: 'CA', latitude: 36.1667, longitude: -121.6667, designation: 'State Park' },
  { id: 'seed_ca_pfeiffer_big_sur', source: 'state', fullName: 'Pfeiffer Big Sur State Park', stateCodes: 'CA', latitude: 36.2404, longitude: -121.7853, designation: 'State Park' },
  { id: 'seed_ca_limekiln', source: 'state', fullName: 'Limekiln State Park', stateCodes: 'CA', latitude: 36.0108, longitude: -121.5222, designation: 'State Park' },
  { id: 'seed_ca_andrew_molera', source: 'state', fullName: 'Andrew Molera State Park', stateCodes: 'CA', latitude: 36.2833, longitude: -121.8500, designation: 'State Park' },
  { id: 'seed_ca_mount_diablo', source: 'state', fullName: 'Mount Diablo State Park', stateCodes: 'CA', latitude: 37.8793, longitude: -121.9143, designation: 'State Park' },
  { id: 'seed_ca_mount_tamalpais', source: 'state', fullName: 'Mount Tamalpais State Park', stateCodes: 'CA', latitude: 37.9018, longitude: -122.5794, designation: 'State Park' },
  { id: 'seed_ca_henry_cowell', source: 'state', fullName: 'Henry Cowell Redwoods State Park', stateCodes: 'CA', latitude: 37.0433, longitude: -122.0522, designation: 'State Park' },
  { id: 'seed_ca_prairie_creek', source: 'state', fullName: 'Prairie Creek Redwoods State Park', stateCodes: 'CA', latitude: 41.3667, longitude: -124.0167, designation: 'State Park' },
  { id: 'seed_ca_del_norte_redwoods', source: 'state', fullName: 'Del Norte Coast Redwoods State Park', stateCodes: 'CA', latitude: 41.7000, longitude: -124.1167, designation: 'State Park' },
  { id: 'seed_ca_humboldt_redwoods', source: 'state', fullName: 'Humboldt Redwoods State Park', stateCodes: 'CA', latitude: 40.3476, longitude: -123.9224, designation: 'State Park' },
  { id: 'seed_ca_lassen_volcanic', source: 'state', fullName: 'Lassen Volcanic State Park', stateCodes: 'CA', latitude: 40.4977, longitude: -121.5081, designation: 'State Park' },
  { id: 'seed_ca_mono_lake', source: 'state', fullName: 'Mono Lake Tufa State Natural Reserve', stateCodes: 'CA', latitude: 37.9833, longitude: -119.1167, designation: 'State Natural Area' },
  { id: 'seed_ca_point_lobos', source: 'state', fullName: 'Point Lobos State Natural Reserve', stateCodes: 'CA', latitude: 36.5167, longitude: -121.9500, designation: 'State Natural Area' },
  { id: 'seed_ca_mcarthur_burney', source: 'state', fullName: 'McArthur-Burney Falls Memorial State Park', stateCodes: 'CA', latitude: 41.0167, longitude: -121.6500, designation: 'State Park' },
  { id: 'seed_ca_mckinley_grove', source: 'state', fullName: 'McKinley Grove State Park', stateCodes: 'CA', latitude: 37.0000, longitude: -119.2333, designation: 'State Park' },
  { id: 'seed_ca_red_rock_canyon', source: 'state', fullName: 'Red Rock Canyon State Park', stateCodes: 'CA', latitude: 35.3667, longitude: -117.9833, designation: 'State Park' },
  { id: 'seed_ca_sonoma_coast', source: 'state', fullName: 'Sonoma Coast State Park', stateCodes: 'CA', latitude: 38.4167, longitude: -123.1167, designation: 'State Park' },
  { id: 'seed_ca_van_damme', source: 'state', fullName: 'Van Damme State Park', stateCodes: 'CA', latitude: 39.2750, longitude: -123.7917, designation: 'State Park' },
  { id: 'seed_ca_tule_elk', source: 'state', fullName: 'Tule Elk State Natural Reserve', stateCodes: 'CA', latitude: 35.8667, longitude: -119.5833, designation: 'State Natural Area' },
  { id: 'seed_ca_antelope_valley_poppy', source: 'state', fullName: 'Antelope Valley California Poppy Reserve', stateCodes: 'CA', latitude: 34.7333, longitude: -118.3167, designation: 'State Park' },
  { id: 'seed_ca_folsom_lake', source: 'state', fullName: 'Folsom Lake State Recreation Area', stateCodes: 'CA', latitude: 38.7167, longitude: -121.1667, designation: 'State Recreation Area' },
  { id: 'seed_ca_auburn', source: 'state', fullName: 'Auburn State Recreation Area', stateCodes: 'CA', latitude: 38.9500, longitude: -121.0833, designation: 'State Recreation Area' },
  { id: 'seed_ca_lake_oroville', source: 'state', fullName: 'Lake Oroville State Recreation Area', stateCodes: 'CA', latitude: 39.5333, longitude: -121.4833, designation: 'State Recreation Area' },
  { id: 'seed_ca_oceano_dunes', source: 'state', fullName: 'Oceano Dunes State Vehicular Recreation Area', stateCodes: 'CA', latitude: 35.0833, longitude: -120.6167, designation: 'State Recreation Area' },
  { id: 'seed_ca_ocotillo_wells', source: 'state', fullName: 'Ocotillo Wells State Vehicular Recreation Area', stateCodes: 'CA', latitude: 33.1500, longitude: -116.1333, designation: 'State Recreation Area' },
  { id: 'seed_ca_gray_whale_cove', source: 'state', fullName: 'Gray Whale Cove State Beach', stateCodes: 'CA', latitude: 37.5500, longitude: -122.5167, designation: 'State Beach' },
  { id: 'seed_ca_half_moon_bay', source: 'state', fullName: 'Half Moon Bay State Beach', stateCodes: 'CA', latitude: 37.4833, longitude: -122.4500, designation: 'State Beach' },
  { id: 'seed_ca_pismo_beach', source: 'state', fullName: 'Pismo State Beach', stateCodes: 'CA', latitude: 35.1333, longitude: -120.6500, designation: 'State Beach' },
  { id: 'seed_ca_carpinteria', source: 'state', fullName: 'Carpinteria State Beach', stateCodes: 'CA', latitude: 34.3833, longitude: -119.5167, designation: 'State Beach' },
  { id: 'seed_ca_san_onofre', source: 'state', fullName: 'San Onofre State Beach', stateCodes: 'CA', latitude: 33.3833, longitude: -117.5667, designation: 'State Beach' },
  { id: 'seed_ca_silver_strand', source: 'state', fullName: 'Silver Strand State Beach', stateCodes: 'CA', latitude: 32.6333, longitude: -117.1333, designation: 'State Beach' },
  { id: 'seed_ca_sunset_beach', source: 'state', fullName: 'Sunset State Beach', stateCodes: 'CA', latitude: 36.9167, longitude: -121.8333, designation: 'State Beach' },
  { id: 'seed_ca_new_brighton', source: 'state', fullName: 'New Brighton State Beach', stateCodes: 'CA', latitude: 36.9750, longitude: -121.9000, designation: 'State Beach' },
  { id: 'seed_ca_columbia', source: 'state', fullName: 'Columbia State Historic Park', stateCodes: 'CA', latitude: 38.0333, longitude: -120.4000, designation: 'State Historic Park' },
  { id: 'seed_ca_old_sacramento', source: 'state', fullName: 'Old Sacramento State Historic Park', stateCodes: 'CA', latitude: 38.5833, longitude: -121.5033, designation: 'State Historic Park' },
  { id: 'seed_ca_sutters_fort', source: 'state', fullName: "Sutter's Fort State Historic Park", stateCodes: 'CA', latitude: 38.5757, longitude: -121.4942, designation: 'State Historic Park' },
  { id: 'seed_ca_fort_ross', source: 'state', fullName: 'Fort Ross State Historic Park', stateCodes: 'CA', latitude: 38.5167, longitude: -123.2333, designation: 'State Historic Park' },
  { id: 'seed_ca_fort_tejon', source: 'state', fullName: 'Fort Tejon State Historic Park', stateCodes: 'CA', latitude: 34.8667, longitude: -118.8833, designation: 'State Historic Park' },
  { id: 'seed_ca_san_juan_bautista', source: 'state', fullName: 'San Juan Bautista State Historic Park', stateCodes: 'CA', latitude: 36.8417, longitude: -121.5375, designation: 'State Historic Park' },
  { id: 'seed_ca_pio_pico', source: 'state', fullName: 'Pio Pico State Historic Park', stateCodes: 'CA', latitude: 33.9833, longitude: -118.0167, designation: 'State Historic Park' },

  // ── Colorado ─────────────────────────────────────────────────────────────
  { id: 'seed_co_arkansas_headwaters', source: 'state', fullName: 'Arkansas Headwaters Recreation Area', stateCodes: 'CO', latitude: 38.5333, longitude: -106.0000, designation: 'State Recreation Area' },
  { id: 'seed_co_barr_lake', source: 'state', fullName: 'Barr Lake State Park', stateCodes: 'CO', latitude: 39.9333, longitude: -104.7500, designation: 'State Park' },
  { id: 'seed_co_boyd_lake', source: 'state', fullName: 'Boyd Lake State Park', stateCodes: 'CO', latitude: 40.4167, longitude: -105.0167, designation: 'State Park' },
  { id: 'seed_co_castlewood_canyon', source: 'state', fullName: 'Castlewood Canyon State Park', stateCodes: 'CO', latitude: 39.3333, longitude: -104.7500, designation: 'State Park' },
  { id: 'seed_co_cherry_creek', source: 'state', fullName: 'Cherry Creek State Park', stateCodes: 'CO', latitude: 39.6333, longitude: -104.8333, designation: 'State Park' },
  { id: 'seed_co_cheyenne_mountain', source: 'state', fullName: 'Cheyenne Mountain State Park', stateCodes: 'CO', latitude: 38.7333, longitude: -104.8500, designation: 'State Park' },
  { id: 'seed_co_crawford', source: 'state', fullName: 'Crawford State Park', stateCodes: 'CO', latitude: 38.7000, longitude: -107.6000, designation: 'State Park' },
  { id: 'seed_co_eldorado_canyon', source: 'state', fullName: 'Eldorado Canyon State Park', stateCodes: 'CO', latitude: 39.9310, longitude: -105.2910, designation: 'State Park' },
  { id: 'seed_co_golden_gate_canyon', source: 'state', fullName: 'Golden Gate Canyon State Park', stateCodes: 'CO', latitude: 39.8167, longitude: -105.4333, designation: 'State Park' },
  { id: 'seed_co_highline_lake', source: 'state', fullName: 'Highline Lake State Park', stateCodes: 'CO', latitude: 39.2333, longitude: -108.8167, designation: 'State Park' },
  { id: 'seed_co_jackson_lake', source: 'state', fullName: 'Jackson Lake State Park', stateCodes: 'CO', latitude: 40.6500, longitude: -104.0833, designation: 'State Park' },
  { id: 'seed_co_james_robb', source: 'state', fullName: 'James M. Robb – Colorado River State Park', stateCodes: 'CO', latitude: 39.0667, longitude: -108.5500, designation: 'State Park' },
  { id: 'seed_co_lathrop', source: 'state', fullName: 'Lathrop State Park', stateCodes: 'CO', latitude: 37.5500, longitude: -104.8167, designation: 'State Park' },
  { id: 'seed_co_mueller', source: 'state', fullName: 'Mueller State Park', stateCodes: 'CO', latitude: 38.8974, longitude: -105.1738, designation: 'State Park' },
  { id: 'seed_co_navajo', source: 'state', fullName: 'Navajo State Park', stateCodes: 'CO', latitude: 37.0167, longitude: -107.6167, designation: 'State Park' },
  { id: 'seed_co_north_sterling', source: 'state', fullName: 'North Sterling State Park', stateCodes: 'CO', latitude: 40.7667, longitude: -103.3167, designation: 'State Park' },
  { id: 'seed_co_paonia', source: 'state', fullName: 'Paonia State Park', stateCodes: 'CO', latitude: 38.9667, longitude: -107.3833, designation: 'State Park' },
  { id: 'seed_co_pearl_lake', source: 'state', fullName: 'Pearl Lake State Park', stateCodes: 'CO', latitude: 40.7667, longitude: -106.8333, designation: 'State Park' },
  { id: 'seed_co_ridgway', source: 'state', fullName: 'Ridgway State Park', stateCodes: 'CO', latitude: 38.2167, longitude: -107.7500, designation: 'State Park' },
  { id: 'seed_co_rifle_falls', source: 'state', fullName: 'Rifle Falls State Park', stateCodes: 'CO', latitude: 39.6667, longitude: -107.7000, designation: 'State Park' },
  { id: 'seed_co_rifle_gap', source: 'state', fullName: 'Rifle Gap State Park', stateCodes: 'CO', latitude: 39.6167, longitude: -107.7667, designation: 'State Park' },
  { id: 'seed_co_roxborough', source: 'state', fullName: 'Roxborough State Park', stateCodes: 'CO', latitude: 39.4264, longitude: -105.0638, designation: 'State Park' },
  { id: 'seed_co_staunton', source: 'state', fullName: 'Staunton State Park', stateCodes: 'CO', latitude: 39.5000, longitude: -105.4167, designation: 'State Park' },
  { id: 'seed_co_state_forest', source: 'state', fullName: 'State Forest State Park', stateCodes: 'CO', latitude: 40.5333, longitude: -105.9000, designation: 'State Park' },
  { id: 'seed_co_steamboat_lake', source: 'state', fullName: 'Steamboat Lake State Park', stateCodes: 'CO', latitude: 40.7833, longitude: -106.9500, designation: 'State Park' },
  { id: 'seed_co_sylvan_lake', source: 'state', fullName: 'Sylvan Lake State Park', stateCodes: 'CO', latitude: 39.6000, longitude: -106.8333, designation: 'State Park' },
  { id: 'seed_co_trinidad_lake', source: 'state', fullName: 'Trinidad Lake State Park', stateCodes: 'CO', latitude: 37.1500, longitude: -104.5667, designation: 'State Park' },
  { id: 'seed_co_vega', source: 'state', fullName: 'Vega State Park', stateCodes: 'CO', latitude: 39.2333, longitude: -107.7833, designation: 'State Park' },
  { id: 'seed_co_yampa_river', source: 'state', fullName: 'Yampa River State Park', stateCodes: 'CO', latitude: 40.4833, longitude: -107.3500, designation: 'State Park' },

  // ── Connecticut ──────────────────────────────────────────────────────────
  { id: 'seed_ct_hammonasset_beach', source: 'state', fullName: 'Hammonasset Beach State Park', stateCodes: 'CT', latitude: 41.2667, longitude: -72.5667, designation: 'State Park' },
  { id: 'seed_ct_rocky_neck', source: 'state', fullName: 'Rocky Neck State Park', stateCodes: 'CT', latitude: 41.3167, longitude: -72.2167, designation: 'State Park' },
  { id: 'seed_ct_sherwood_island', source: 'state', fullName: 'Sherwood Island State Park', stateCodes: 'CT', latitude: 41.1167, longitude: -73.3333, designation: 'State Park' },
  { id: 'seed_ct_silver_sands', source: 'state', fullName: 'Silver Sands State Park', stateCodes: 'CT', latitude: 41.2167, longitude: -73.0667, designation: 'State Park' },
  { id: 'seed_ct_macedonia_brook', source: 'state', fullName: 'Macedonia Brook State Park', stateCodes: 'CT', latitude: 41.7333, longitude: -73.4833, designation: 'State Park' },
  { id: 'seed_ct_talcott_mountain', source: 'state', fullName: 'Talcott Mountain State Park', stateCodes: 'CT', latitude: 41.8667, longitude: -72.8167, designation: 'State Park' },
  { id: 'seed_ct_devils_hopyard', source: 'state', fullName: "Devil's Hopyard State Park", stateCodes: 'CT', latitude: 41.4667, longitude: -72.3333, designation: 'State Park' },
  { id: 'seed_ct_kent_falls', source: 'state', fullName: 'Kent Falls State Park', stateCodes: 'CT', latitude: 41.7667, longitude: -73.4167, designation: 'State Park' },
  { id: 'seed_ct_wadsworth_falls', source: 'state', fullName: 'Wadsworth Falls State Park', stateCodes: 'CT', latitude: 41.5167, longitude: -72.7167, designation: 'State Park' },
  { id: 'seed_ct_collis_huntington', source: 'state', fullName: 'Collis P. Huntington State Park', stateCodes: 'CT', latitude: 41.3167, longitude: -73.3833, designation: 'State Park' },
  { id: 'seed_ct_sleeping_giant', source: 'state', fullName: 'Sleeping Giant State Park', stateCodes: 'CT', latitude: 41.4167, longitude: -72.9000, designation: 'State Park' },
  { id: 'seed_ct_lake_waramaug', source: 'state', fullName: 'Lake Waramaug State Park', stateCodes: 'CT', latitude: 41.7167, longitude: -73.3667, designation: 'State Park' },
  { id: 'seed_ct_black_rock', source: 'state', fullName: 'Black Rock State Park', stateCodes: 'CT', latitude: 41.5667, longitude: -73.1167, designation: 'State Park' },
  { id: 'seed_ct_burr_pond', source: 'state', fullName: 'Burr Pond State Park', stateCodes: 'CT', latitude: 41.8833, longitude: -73.0500, designation: 'State Park' },
  { id: 'seed_ct_bigelow_hollow', source: 'state', fullName: 'Bigelow Hollow State Park', stateCodes: 'CT', latitude: 41.9833, longitude: -72.1167, designation: 'State Park' },
  { id: 'seed_ct_hopeville_pond', source: 'state', fullName: 'Hopeville Pond State Park', stateCodes: 'CT', latitude: 41.5667, longitude: -71.9333, designation: 'State Park' },
  { id: 'seed_ct_hammonasset_preserve', source: 'state', fullName: 'Hammonasset Natural Area Preserve', stateCodes: 'CT', latitude: 41.2667, longitude: -72.5500, designation: 'State Natural Area' },
  { id: 'seed_ct_pachaug', source: 'state', fullName: 'Pachaug State Forest', stateCodes: 'CT', latitude: 41.5667, longitude: -71.8833, designation: 'State Forest' },
  { id: 'seed_ct_natchaug', source: 'state', fullName: 'Natchaug State Forest', stateCodes: 'CT', latitude: 41.8833, longitude: -72.1333, designation: 'State Forest' },
  { id: 'seed_ct_tunxis', source: 'state', fullName: 'Tunxis State Forest', stateCodes: 'CT', latitude: 41.7667, longitude: -72.9667, designation: 'State Forest' },
  { id: 'seed_ct_meshomasic', source: 'state', fullName: 'Meshomasic State Forest', stateCodes: 'CT', latitude: 41.6167, longitude: -72.4500, designation: 'State Forest' },
  { id: 'seed_ct_gillette_castle', source: 'state', fullName: 'Gillette Castle State Park', stateCodes: 'CT', latitude: 41.4333, longitude: -72.4333, designation: 'State Historic Park' },
  { id: 'seed_ct_fort_trumbull', source: 'state', fullName: 'Fort Trumbull State Park', stateCodes: 'CT', latitude: 41.3500, longitude: -72.1000, designation: 'State Historic Park' },

  // ── Delaware ─────────────────────────────────────────────────────────────
  { id: 'seed_de_cape_henlopen', source: 'state', fullName: 'Cape Henlopen State Park', stateCodes: 'DE', latitude: 38.7897, longitude: -75.1028, designation: 'State Park' },
  { id: 'seed_de_delaware_seashore', source: 'state', fullName: 'Delaware Seashore State Park', stateCodes: 'DE', latitude: 38.6167, longitude: -75.0611, designation: 'State Park' },
  { id: 'seed_de_fenwick_island', source: 'state', fullName: 'Fenwick Island State Park', stateCodes: 'DE', latitude: 38.4514, longitude: -75.0519, designation: 'State Park' },
  { id: 'seed_de_harrington_beach', source: 'state', fullName: 'Harrington Beach State Park', stateCodes: 'DE', latitude: 38.9167, longitude: -75.5833, designation: 'State Park' },
  { id: 'seed_de_brandywine_creek', source: 'state', fullName: 'Brandywine Creek State Park', stateCodes: 'DE', latitude: 39.7833, longitude: -75.5500, designation: 'State Park' },
  { id: 'seed_de_white_clay_creek', source: 'state', fullName: 'White Clay Creek State Park', stateCodes: 'DE', latitude: 39.7000, longitude: -75.7500, designation: 'State Park' },
  { id: 'seed_de_lums_pond', source: 'state', fullName: 'Lums Pond State Park', stateCodes: 'DE', latitude: 39.5500, longitude: -75.7333, designation: 'State Park' },
  { id: 'seed_de_killens_pond', source: 'state', fullName: 'Killens Pond State Park', stateCodes: 'DE', latitude: 38.9833, longitude: -75.5667, designation: 'State Park' },
  { id: 'seed_de_trap_pond', source: 'state', fullName: 'Trap Pond State Park', stateCodes: 'DE', latitude: 38.5333, longitude: -75.4833, designation: 'State Park' },
  { id: 'seed_de_bellevue', source: 'state', fullName: 'Bellevue State Park', stateCodes: 'DE', latitude: 39.7833, longitude: -75.4833, designation: 'State Park' },
  { id: 'seed_de_holts_landing', source: 'state', fullName: 'Holts Landing State Park', stateCodes: 'DE', latitude: 38.5500, longitude: -75.1667, designation: 'State Park' },
  { id: 'seed_de_fort_delaware', source: 'state', fullName: 'Fort Delaware State Park', stateCodes: 'DE', latitude: 39.5781, longitude: -75.5681, designation: 'State Historic Park' },
  { id: 'seed_de_fort_dupont', source: 'state', fullName: 'Fort DuPont State Park', stateCodes: 'DE', latitude: 39.5750, longitude: -75.5833, designation: 'State Historic Park' },
  { id: 'seed_de_auburn_valley', source: 'state', fullName: 'Auburn Valley State Park', stateCodes: 'DE', latitude: 39.7833, longitude: -75.6500, designation: 'State Historic Park' },
  { id: 'seed_de_blackbird_forest', source: 'state', fullName: 'Blackbird State Forest', stateCodes: 'DE', latitude: 39.3667, longitude: -75.6333, designation: 'State Forest' },
];

export function toFullPark(s: SeedPark): Park {
  return {
    ...s,
    description: '',
    imageUrl: null,
    activities: [],
    entranceFeeCents: 0,
    rawJson: '{}',
    lastSynced: NOW,
  };
}

export { SEEDS };
